// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dummy.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Dummy struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dummy) Reset()         { *m = Dummy{} }
func (m *Dummy) String() string { return proto.CompactTextString(m) }
func (*Dummy) ProtoMessage()    {}
func (*Dummy) Descriptor() ([]byte, []int) {
	return fileDescriptor_f61c4c74b7db52b0, []int{0}
}

func (m *Dummy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dummy.Unmarshal(m, b)
}
func (m *Dummy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dummy.Marshal(b, m, deterministic)
}
func (m *Dummy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dummy.Merge(m, src)
}
func (m *Dummy) XXX_Size() int {
	return xxx_messageInfo_Dummy.Size(m)
}
func (m *Dummy) XXX_DiscardUnknown() {
	xxx_messageInfo_Dummy.DiscardUnknown(m)
}

var xxx_messageInfo_Dummy proto.InternalMessageInfo

func (m *Dummy) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Dummy)(nil), "greet.Dummy")
}

func init() { proto.RegisterFile("dummy.proto", fileDescriptor_f61c4c74b7db52b0) }

var fileDescriptor_f61c4c74b7db52b0 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x29, 0xcd, 0xcd,
	0xad, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x2f, 0x4a, 0x4d, 0x2d, 0x51, 0x12,
	0xe7, 0x62, 0x75, 0x01, 0x89, 0x0a, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0xf0, 0x06, 0x31, 0x65, 0xa6, 0x18, 0xf1, 0x71, 0xf1, 0x80, 0x25, 0x82, 0x53, 0x8b, 0xca, 0x32,
	0x93, 0x53, 0x9d, 0x74, 0xa2, 0xb4, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73,
	0xf5, 0x8b, 0x4a, 0x0a, 0x12, 0x8d, 0x4c, 0xf5, 0xd3, 0x8b, 0x0a, 0x92, 0x75, 0x53, 0x2b, 0x12,
	0x73, 0x0b, 0x72, 0x52, 0xf5, 0xc1, 0x06, 0xea, 0x83, 0x4d, 0x4f, 0x62, 0x03, 0x53, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x29, 0x8a, 0x54, 0x73, 0x00, 0x00, 0x00,
}
